name: ci

on: [push]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install
      run: yarn
      env:
        CI: true
    - run: yarn build
      env:
        CI: true
    - run: yarn test
      env:
        CI: true
